# Generated by Django 3.0.7 on 2020-07-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200705_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('books', models.ManyToManyField(related_name='friend_book', to='p_library.Book')),
            ],
        ),
    ]
