# Generated by Django 3.0.7 on 2020-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(null=True, related_name='friend_book', to='p_library.Book'),
        ),
    ]
