# Generated by Django 3.0.7 on 2020-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200712_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='friend_book', to='p_library.Book'),
        ),
    ]
